### PR TITLE
Added s3 backup options for acl, storage class and sse

### PR DESCRIPTION
**Pull request by robbruce**
Due to some bucket policies, the backup process can fail unless these options can be controlled.  Based config naming standards from the s3 output plugin.

### CODE REVIEW

**Comment by Psykyck** [comment]
Any updates on this? Was specifically looking to add sse to the backup process.

**Comment by robbruce** [comment]
> trigger CLA check please

This was signed on the 15th March 2018

**Comment by robbruce** [comment]
Resigned with both email addresses I use

**Comment by robbruce** [comment]
Closed as CLA is failing due to old email used, will re-issue

**Pull request closed without merging**
