### PR TITLE
Add relative S3 path to events

### PR DESCRIPTION
**Pull request by todd534**
Attempting to address comments made here: https://github.com/logstash-plugins/logstash-input-s3/pull/76#issuecomment-203039326

### CODE REVIEW

**Comment by todd534** [comment]
The following three issues and four pull requests all ask for or implement the same feature. 

https://github.com/logstash-plugins/logstash-input-s3/issues/88
https://github.com/logstash-plugins/logstash-input-s3/issues/104
https://github.com/logstash-plugins/logstash-input-s3/issues/39
https://github.com/logstash-plugins/logstash-input-s3/pull/63/files
https://github.com/logstash-plugins/logstash-input-s3/pull/41
https://github.com/logstash-plugins/logstash-input-s3/pull/26
https://github.com/logstash-plugins/logstash-input-s3/pull/3/files

This pull improves on those by, as best as I could tell, following the naming convention preferred by the maintainers, and adding a test. 

I'm happy to make further tweaks as needed, but I think the desire is there and I'd love to shepherd this through.

**Comment by todd534** [comment]
It seems like maybe https://github.com/logstash-plugins/logstash-input-s3/pull/87 (or I guess really the original one, I think it's #84) implements this as an unmentioned bonus? I think those also populate the metadata with bucket and last modified time. If the chances are better of that getting merged, that's awesome. 

If, as a big refactor, that's blocking other changes until it lands, makes sense to focus there. Is there anything that needs to be done to help that one along?

If that's not going to move forward, would still love to get this in in the meantime.

**Comment by nbanerje** [comment]
@jsvd @ph we have a client that requires this change to be in a release for them to use it in their production environment. Could you help me and @todd534 figure out how fix the build errors related to versions and any other requirements to get this PR merged and deployed?

**Comment by todd534** [comment]
@ph Any chance we could move on this? I know that it's only a subset of the related functionality provided by #84, but it does conform to the same naming convention, and would be a useful stop-gap for people until the refactor lands.

**Comment by ph** [comment]
@todd534 @nbanerje I am OK with the changes, could we add some unit test for that changes to make sure we don't add any regression?

**Comment by todd534** [comment]
@ph Hm. It seemed to me that the test I added (https://github.com/logstash-plugins/logstash-input-s3/pull/105/files#diff-48411412ccb7d848eae88f57b8e3b007R216) should prevent regressions? 

I'm sort of not sure how to add a more direct unit test of the `process_local_log` method. To do so I would have to create some valid log file, and at that point using the existing framework for testing event processing feels cleaner to me. But if it's a sticking point, let me know and I'll try to find a way to do that.

**Comment by todd534** [comment]
@ph thoughts?

**Comment by ph** [comment]
Sorry for the delay, 3.1.3 is now up on rubygems

**Comment by todd534** [comment]
:heart_eyes: Thanks @ph!

**Pull request merged**
