### PR TITLE
Add gzip_pattern config option

### LINKED ISSUE #165: Optional flag to decompress file without having 'gz' extention
We are using S3 input plugin to pull data from S3, we are using kinesis firehose to push data to S3, which does not adds 'gz' extension to the files, but data is in zipped format. 

S3 input plugin is pulling data from S3 it can only decompress the data which has gz as extension since while code walk through we we notice there is a condition checking 'gz' as extension then only it decompress the file data.

We do not want to maintain the custom plugin at our end just for small change.

I just wanted to ask can we add a flag over there, which can be set as configuration and used with that condition, so that even files which use can set intentionally to decompress files does not have 'gz' extension or with any extension.

Can you provide such feature as same plugin or can we contribute to this input plugin, if yes how and what is the process for the same?

### PR DESCRIPTION
**Pull request by blangenfeld**
Just happened to run into the same problem as #165, as we're working with files named e.g. `data.json.gz.1`, `data.json.gz.2`.

resolves #165

### CODE REVIEW

**Comment by blangenfeld** [comment]
Done! 👍

**Comment by blangenfeld** [comment]
@jsvd , is the PR good to go and looking good to you guys? I'd love to ditch our private fork. :sweat_smile:

**Comment by JoshiiSinfield** [comment]
HI,

We're encountering this, and would love to see it merged soon!

Cheers,
Josh

**Comment by gurupritmukhraiya** [comment]
Any updates?

**Comment by TC-sChandramohan** [comment]
Hi, 
When can we see this merged? Facing the same issue and would love to see this merged.
Any estimates/timeline?

thanks,

**Pull request merged**
