### PR TITLE
Make theading fork functional

### PR DESCRIPTION
**Pull request by brandond**
Also upgrade to aws-sdk v2 and logstash plugin API v2
This is pursuant to additional work discussed in #84

### CODE REVIEW

**Comment by karmi** [comment]
Hi @brandond, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-s3/pull/87.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by brandond** [comment]
@karmi Sorry, was working in a temporary environment without the proper author info. Should be fixed now.

**Comment by jordansissel** [comment]
Hmm.. Travis failed due to having the wrong version of java, it looks like?

LoadError: JRuby ext built for wrong Java version in `JrubyEventExtService': java.lang.UnsupportedClassVersionError: JrubyEventExtService : Unsupported major.minor version 52.0

**Comment by jordansissel** [comment]
Still failing, now due to recent commit having invalid configuration for travis: https://travis-ci.org/logstash-plugins/logstash-input-s3/builds/159712281

**Comment by brandond** [comment]
@jordansissel looks like there are some missing changes to the Travis config. Added. I'll rebase to hide the churn when I get the tests working.

**Comment by jordansissel** [comment]
@brandond cool :)

**Comment by brandond** [comment]
@jordansissel What's the current magic invocation for running rspec locally? looks like `bin/logstash rspec` no longer works.

**Comment by brandond** [comment]
These specs are a mess; some of them don't even match what the code is actually doing. I'll clean up what I can.

**Comment by brandond** [comment]
@ph got everything working and rebased to hide the churn. 

I had to pull the integration test out 'cause it seems to depend on having access to a private bucket - couldn't figure out what it was expecting, and all the credentials stuff is now handled by the aws mixin anyway.

**Comment by ph** [comment]
@brandond I was fixing other, issue, the integration tests need to be completely redone they dont match at all.

**Comment by ph** [comment]
@brandond I should be able to test it tomorrow and finish this PR was on a 5.0 beta issue.

**Comment by brandond** [comment]
Looks like there's a race condition in the IgnoreOlderThan validator - if the test runs too fast it fails due to the time not differing sufficiently. Will fix.

**Comment by brandond** [comment]
@ph ok, should be all set now - I'm going to stop tinkering with it and leave this unit of work as a single PR. I will say that the new SinceDB that remembers each individual object is going to be a performance issue on large buckets, but I'm not trying to fix anything here, just get it working as is so that I have a clean starting point for an additional PR.

**Comment by runningman84** [comment]
@ph and @jordansissel what about merging this stuff?

**Pull request closed without merging**
