### PR TITLE
Fix/ignore empty file

### LINKED ISSUE #2: inputs/s3.rb: Keep attempting and failing to parse the same gz file if it's corrupted
Moved from https://github.com/elasticsearch/logstash/issues/2090

I'm using logstash v1.4.2. S3 input crashes if a bucket contains a zero-byte gz file. (throwing an error "Error: not in gzip format".) Then, logstash will retry indefinitely since sincedb is not updated.

I've made a change in `list_new` to skip empty S3 objects (attached code below) to address this particular issue but it may be a good idea to have more robust error handling.

``` ruby
  private
  def list_new(since=nil)

    if since.nil?
      since = Time.new(0)
    end

    objects = {}
    @s3bucket.objects.with_prefix(@prefix).each do |log|
      # original code in v1.4.2
      # if log.last_modified > since
      if log.last_modified > since && log.content_size > 0
        objects[log.key] = log.last_modified
      end
    end

    return sorted_objects = objects.keys.sort {|a,b| objects[a] <=> objects[b]}

  end # def list_new
```

### PR DESCRIPTION
**Pull request by ph**
Fixes #2

### CODE REVIEW

**Comment by watollop** [comment]
It will be so great to have this feature. Any news?

**Comment by spohn-acc** [comment]
Running into the same issue, the error message looks like this:
`[2017-12-16T08:46:31,480][ERROR][logstash.inputs.s3       ] Gzip codec: We cannot uncompress the gzip file ..... etc...`
And we see the file is a zero size .gz file.   

When this error is triggered, no more files are processed by the plugin, so the whole data load gets stuck.  The following message is:
`[2017-12-16T08:46:31,480][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.`

The only way around is to remove the file to get all the processing going again.

**Comment by jsvd** [comment]
LGTM

**Comment by jsvd** [comment]
merged in https://github.com/logstash-plugins/logstash-input-s3/commit/fe49a605638a28e522b93718a31d1ed08365a084

**Pull request closed without merging**
