### PR TITLE
Updating aws-sdk to v3

### LINKED ISSUE #207: using fine grained service account IAM roles in EKS
Hi,
I'm using [service account iam roles](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) in amazon EKS, but I'm not able to get logstash s3 working using an IAM role.

I can see the environment variables in the pod:
- AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token 

- AWS_ROLE_ARN: arn:aws:iam::0123456789:role/logstash-cloudfront

The input config:
```
input {
      s3 {
        role_arn => "${AWS_ROLE_ARN}"
        bucket => "logs-cloudfront"
        prefix => "staging"
        region => "us-west-1"
      }
}
```
Is there anyway for the plugin to read the identity toke file?
Thanks in advance

### PR DESCRIPTION
**Pull request by ageekymonk**
Fixes #207 . V2 api does not support AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN value from environment. The fix is to move to v3 api.

### CODE REVIEW

**Comment by kares** [comment]
Thanks ramz, do you know if the 2 versions (aws-sdk v2 + bits of v3) could co exist in one bundle of gems?

**Comment by dggreenbaum** [comment]
@kares Amazon's readme says that should be ok:

https://github.com/aws/aws-sdk-ruby#upgrading-guide

> Version 3 modularizes the monolithic SDK into service specific gems. Aside from gem packaging differences, version 3 interfaces are backwards compatible with version 2.

**Comment by dominik-ba** [comment]
will this become a new release? :)

**Comment by ahmedkhattab** [comment]
we see a Travis CI failed test for ES version 6.x for this merge. Is someone still following up on this to have a release ?

**Pull request merged**
