### PR TITLE
Added support for .gzip extension

### PR DESCRIPTION
**Pull request by divdevar**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by karmi** [comment]
Hi @divdevar, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-s3/pull/115.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by karmi** [comment]
Hi @divdevar, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-s3/pull/115.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by divdevar** [comment]
Hi ,

I registered with the same email twice. Sorry about that. Could you help me
fix this ?

Thanks,
Divya

**Comment by divdevar** [comment]
This pr is similar to https://github.com/logstash-plugins/logstash-input-s3/pull/113. But I have added tests for the solution.

**Comment by divdevar** [comment]
@jordansissel Will it be possible to merge this PR ? I really need the feature to pull .gzip files.

**Pull request closed without merging**
