### PR TITLE
Upgrade to aws-sdk v2 to get feature improvements

### PR DESCRIPTION
**Pull request by DanielRedOak**
Upgraded spec tests + code to use aws-sdk v2.  This then improves processing by a large margin as v1 repeated api calls for every object when .last_modified was used.  v2 requires only a single call for every 1000 objects so on a bucket with 1000 objects, api calls are down to 1 from 1001 just for the last_modified and bucket.objects calls.  Pagination is included in the sdk as well so this plugin now supports buckets with over 1000 objects.

Additionally added a debug message to show the length of objects[] as things are being added.

There was also a bug where the 'message' field was assumed present and used for checks to determine if the 'event_is_metadata'.  Since this is not a required field per https://logstash.jira.com/browse/LOGSTASH-675 we should check for nil before assuming its present.  This manifested itself specifically when using the cloudtrail codec as there is no message included in resulting events.

### CODE REVIEW

**Comment by ph** [comment]
Will try to test asap, with the elastic{on} I am a bit behind.

**Comment by shaharmor** [comment]
Any estimate on when this will be merged?

**Comment by DanielRedOak** [comment]
Just fyi, I've been using this code + the extras for threading for our cloudtrail and other logs over the past week.  Seems to be chugging along nicely.  If interested: https://github.com/DanielRedOak/logstash-input-s3/tree/multithread

Looking forward to hopefully getting this merged, then submitting a PR for the threaded version!

**Comment by rabidscorpio** [comment]
+1

**Comment by netoneko** [comment]
Any progress on merging this?

**Comment by ph** [comment]
With 1.5 release just around the corner I am looking at this :)
@DanielRedOak Awesome work!

**Comment by sgzijl** [comment]
+1 (will this be merged? it works perfectly here and makes me very very happy!)

**Comment by ph** [comment]
@DanielRedOak Look great, lets get this thing in :)

Would you mind rebasing your PR?  Also can you test it with https://github.com/logstash-plugins/logstash-mixin-aws/pull/13 ?  This PR add the aws-sdk v2 api and remain compatible with plugins that use v1. Small changes are necessary in your PR to make it work with it:

- remove the dependencies from your gemspec.
- remove the `aws_service_endpoint` method.
- include the `LogStash::PluginMixins::AwsConfig::V2` instead of LogStash::PluginMixins::AwsConfig

**Comment by nikolay** [comment]
@DanielRedOak Are you gonna wrap this up? We need it badly!

**Comment by xelibrion** [comment]
+1, would be great to have it merged!

**Comment by DanielRedOak** [comment]
@ph yea, I really want to finish this up.  Been busy with a new job so its definitely been on the back burner.  I'll try for this week or early next.

**Comment by ph** [comment]
@DanielRedOak I'll give a hand I've been busy with logstash-core issues :(

**Comment by DanielRedOak** [comment]
For real this time, I have it checked out and will work on it!  Shouldn't take much work, I just have to squeeze it in

**Comment by jmccarty3** [comment]
any update on this?

**Comment by DanielRedOak** [comment]
I've been working with the aws sdk again for some work related items, so it's turned out to be a good time to finish this up for folks.  I'll work through the needed changes then rebase for the PR.  Sorry I've been slacking.

**Comment by KptnKMan** [comment]
@DanielRedOak This bug is killing my ELK project on different levels. I'm seeing the same issues in Logstash2.0 even.
Can anyone provide any indication of when this can be implemented, or if there is some method I can test your WIP v2 implementation?

**Comment by sstarcher** [comment]
what is this waiting for?

**Comment by smashew** [comment]
pwease? I have a similar issue.

**Comment by sstarcher** [comment]
@smashew if your interested I rebased @DanielRedOak https://github.com/DanielRedOak/logstash-input-s3/tree/multithread changes for aws-sdk v2 and his multithreading changes onto logstash-input-s3 HEAD onto https://github.com/sstarcher/logstash-input-s3/

I have been running it for a few days now.  It is performing much much better.  I can't seem to get it to run  more than on 3 cores though so it's still limited.  Although that may be a user error.

**Comment by KptnKMan** [comment]
Omg @sstarcher, thank you! Is there any special compiling required for this
or can I just clone the repository and use the files?

I'm happy to test!

**Comment by sstarcher** [comment]
I ran everything inside of a docker container.  The following should install everything for you
```
    curl -SL https://github.com/sstarcher/logstash-input-s3/archive/master.tar.gz \
    | tar xzC / &&\
    cd logstash-input-s3-master/ &&\
    gem build logstash-input-s3.gemspec &&\
    /opt/logstash/bin/plugin install /logstash-input-s3-master/logstash-input-s3-*.gem &&\
    rm -rf /logstash-input-s3-master
```

**Comment by KptnKMan** [comment]
@sstarcher @DanielRedOak I've finally had a chance to test this (S3 bucket with 105000+ items) and it appears to have worked. Churned through the whole bucket in a matter of hours, where it never finished before.

Setup is fresh install of LS2.1.1, and ES2.1.1.
Plugins installed: logstash-codec-cloudtrail
No other modifications.

Its worth noting that logstash crashed overnight, but I have not looked into exactly why that was.

**Comment by DanielRedOak** [comment]
Worked on this some more and was rebasing with current master.  Unfortunately I am seeing issues now with spec tests reading in 0 line files so I need to troubleshoot more.  I'm going to be on vacation for a bit, so I will follow up after!

**Comment by argais** [comment]
Anxious for this! Got a cloudtrail bucket with 13.7 million files waiting :D

**Comment by argais** [comment]
I tried using @sstarcher fork but it crashed after 12 hours reading the bucket. Guess I'll have to wait :)

**Comment by sstarcher** [comment]
@argais interesting the only time I have noticed it crash on me so far was when something else was processing the same file.

**Comment by KptnKMan** [comment]
FYI @DanielRedOak @sstarcher @argais
I've been using the recommended @sstarcher branch for about a month now, and it works great. I've processed tens of millions of CloudTrail items with this and it's so far been solid.
Running it on a vanilla install of LS2.1.1 interacting with ES2.1.1

When is someone going to look into merging this into an actual release?

**Comment by chad-upton** [comment]
Seriously would love to get this merged.

**Comment by Centurion89** [comment]
I'm getting "TypeError: can't convert nil into String" errors on a seemingly random basis while the logs are outputting and can't seem to figure out the root cause. Here's the stack trace:

```
TypeError: can't convert nil into String
               join at org/jruby/RubyArray.java:1892
               join at org/jruby/RubyArray.java:1898
            extract at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/util/buftok.rb:87
             decode at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35
  process_local_log at /opt/logstash/vendor/local_gems/100c7c56/logstash-input-s3-2.0.3/lib/logstash/inputs/s3.rb:214
               each at org/jruby/RubyIO.java:3542
    read_plain_file at /opt/logstash/vendor/local_gems/100c7c56/logstash-input-s3-2.0.3/lib/logstash/inputs/s3.rb:285
               open at org/jruby/RubyIO.java:1183
    read_plain_file at /opt/logstash/vendor/local_gems/100c7c56/logstash-input-s3-2.0.3/lib/logstash/inputs/s3.rb:284
          read_file at /opt/logstash/vendor/local_gems/100c7c56/logstash-input-s3-2.0.3/lib/logstash/inputs/s3.rb:279
  process_local_log at /opt/logstash/vendor/local_gems/100c7c56/logstash-input-s3-2.0.3/lib/logstash/inputs/s3.rb:208
        process_log at /opt/logstash/vendor/local_gems/100c7c56/logstash-input-s3-2.0.3/lib/logstash/inputs/s3.rb:347
      process_files at /opt/logstash/vendor/local_gems/100c7c56/logstash-input-s3-2.0.3/lib/logstash/inputs/s3.rb:165
```

**Comment by Centurion89** [comment]
This also doesn't seem to be respecting my sincedb file and is outputting events that are days before the listed timestamp in my sincedb

**Comment by bsideup** [comment]
:+1:

**Comment by bsideup** [comment]
@DanielRedOak looks like PR missing CLA, could you please sign it?

**Comment by ph** [comment]
@DanielRedOak Can you rebase it? There is multiples people testing this code and I am confident in merging it, the cla is fine.

**Comment by DanielRedOak** [comment]
Will do this morning.  I have tests working for most of it, but kept getting 0 line input so I must be missing something there.

**Comment by DanielRedOak** [comment]
Think this should be good now, rebasing with a year of changes was a bit of fun :)

**Comment by sstarcher** [comment]
@DanielRedOak I'm certainly interested in the multithreading, but you may want to have that in another PR as to not slow this one down ;)

**Comment by suyograo** [comment]
@DanielRedOak I ran the tests and they fail. Can you please take a look:

```
suyog@machine:~/ws/elastic/ls_plugins/logstash-input-s3 (pr/25)$ bundle exec rspec
....

Failed examples:

rspec ./spec/inputs/s3_spec.rb:66 # LogStash::Inputs::S3#get_s3object with deprecated credentials option should instantiate AWS::S3 clients with a proxy set
rspec ./spec/inputs/s3_spec.rb:88 # LogStash::Inputs::S3#get_s3object with modern access key options should instantiate AWS::S3 clients with a proxy set
rspec ./spec/inputs/s3_spec.rb:245 # LogStash::Inputs::S3 when working with logs when event doesn't have a `message` field should process events
rspec ./spec/inputs/s3_spec.rb:245 # LogStash::Inputs::S3 when working with logs plain text should process events
rspec ./spec/inputs/s3_spec.rb:245 # LogStash::Inputs::S3 when working with logs encoded should process events
rspec ./spec/inputs/s3_spec.rb:245 # LogStash::Inputs::S3 when working with logs compressed should process events
rspec ./spec/inputs/s3_spec.rb:250 # LogStash::Inputs::S3 when working with logs compressed deletes the temporary file
rspec ./spec/inputs/s3_spec.rb:245 # LogStash::Inputs::S3 when working with logs cloudfront should process events
```

**Comment by suyograo** [comment]
Tests on master run successfully, no failures.

**Comment by DanielRedOak** [comment]
Yea, I mentioned above that they fail probably due to issues stubbing the
get on the object. @ph wanted me to rebase anyways since many people have
used it successfully.  I'll still give it another look when I get some more
time as it bothers me :)

**Comment by suyograo** [comment]
Thanks @DanielRedOak would love to get this merged and new version published asap :)

**Comment by ph** [comment]
Thanks @DanielRedOak

**Comment by RichardN** [comment]
Hello.  I was looking at what is required to get the tests from this pull request working.   One issue is that the "credentials" config setting here has a conflict with a private method called "credentials" in the logstash-mixin-aws gem.   If this is fixed, my fork of this repo https://github.com/RichardN/logstash-input-s3 has tests that pass (it also fully makes use of the fixed logstash-mixin-aws (I've created a pull request for the mixin - https://github.com/logstash-plugins/logstash-mixin-aws/pull/20)

**Comment by PhaedrusTheGreek** [comment]
+1 for the merge

**Comment by ryantanner** [comment]
Is this going to get merged any time soon?  We were about to put Logstash in production when we found it just can't handle our volume.

**Comment by jsvd** [comment]
Current state of this was that the PR had tests failing, so it couldn't be merged, and obviously by now has again diverged from master :(

**Comment by 0x4D31** [comment]
any update?
I tested @sstarcher branch for a few hours, and it seems it works great!

**Comment by DanielRedOak** [comment]
I'll see if I can pull things in again and rebase to get everything aligned and include fixes for the spec tests so we can hopefully close this out.  Unfortunately since we don't use Logstash at my current job I don't get any time during the workdays to get things cleaned up.  I'll shoot to get something done and merged in again by next week for the sdk upgrade.

**Comment by energycoaching** [comment]
+1

**Comment by DanielRedOak** [comment]
Should be good to go now. Hopefully it will be merged before we pile up some more conflicts :)

**Comment by suyograo** [comment]
@DanielRedOak thanks for your efforts here. Will merge this.

**Comment by emckean** [comment]
dumb q: to get these changes should I be cloning master and installing it (as in sstarcher's instructions above) or will basic logstash-plugin install work?

**Comment by sstarcher** [comment]
@emckean looks like the changes are now in release 3.1.1

**Comment by occelebi** [comment]
I need it so badly. But could not get managed to install. I tried with bin/plugin install, update, downloading it locally and pack unpack but no success. Can somebody refer a resource that explains all steps including installing gems ruby jruby bundle from scratch ? 

OS: Ubuntu 14.04
LS: 2.2.2
ruby 1.9.3p484
jruby 1.5.6
gem 1.8.23
bundle 1.13.6

@sstarcher I also tried with your solution but gem build fails:

`root@elk-stack:/opt/logstash/logstash-input-s3-3.1.1# gem build logstash-input-s3.gemspec 
Invalid gemspec in [logstash-input-s3.gemspec]: undefined method metadata=' for #<Gem::Specification name=logstash-input-s3 version=3.1.1>
ERROR:  Error loading gemspec. Aborting.`

**Pull request merged**
