### PR TITLE
Make logstash-input-s3 compatible with an object store different than…

### PR DESCRIPTION
**Pull request by djannot**
… Amazon

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by djannot** [comment]
Just signed the CLA

**Comment by PDRMAN** [comment]
We would like to use this plugin as well. In the mean time as a work around we have set up MinFS (https://github.com/minio/minfs ) to have the buckets mounted as mount points on Linux. This works well with LogStash for READING data in.

**Comment by cgroschupp** [comment]
@ph @jsvd Can you please give some feedback on this PR.

**Comment by jsvd** [comment]
solved by https://github.com/logstash-plugins/logstash-mixin-aws/pull/32

**Pull request closed without merging**
