### PR TITLE
Add bucket and key as fields

### PR DESCRIPTION
**Pull request by ph**
fixes: https://github.com/logstash-plugins/logstash-input-s3/issues/39
moved from https://github.com/elastic/logstash/pull/1842

### CODE REVIEW

**Comment by BVulaj** [comment]
Any time estimate on releasing this feature?  This is something that's been missing that we've really been hoping for.  I'd rather wait for a release than pull from the branch if it's going to be somewhat soon.

Thanks!

**Comment by deoxxa** [comment]
This would certainly be nice to have.

**Comment by pliljenberg** [comment]
This would be great to get merged and released.

**Comment by deoxxa** [comment]
This missing feature (and the inactivity surrounding it) actually prompted me to write my own log aggregation tool. I'm not sure whether that's a good thing or a bad thing.

**Comment by jeffxor** [comment]
Any one going to actually merge and close this issue? Been open since May I would prefer to use approved code.

**Comment by ph** [comment]
done in 3.1.3.

**Pull request closed without merging**
