### PR TITLE
Fix bug with :aws_credentials_file

### PR DESCRIPTION
**Pull request by rfkrocktk**
This plugin is lagging  behind the S3 output plugin and the :aws_credentials_file parameter doesn't work here. I've gone through, optimized the source code, and had it use the AWS mixin's handling of parsing AWS credentials.

### CODE REVIEW

**Comment by ph** [comment]
Thanks @rfkrocktk 

Would you mind doing step 2 of the contributing guide? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by rfkrocktk** [comment]
@ph Can I just disown and disavow all rights to the code contained in this pull request instead? Can I license my contribution via this pull request with MIT and bypass the need for my signature on a document? Kind of weird, if you ask me.

**Comment by ph** [comment]
@rfkrocktk as a project we make all the pull request go through the same [process](https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md) and part of it is to sign our CLA. Unfortunately we do not accept any code contributions without it. Signing the CLA protects all the users of logstash of some IP litigation, you can learn more about it at https://www.elastic.co/contributor-agreement/

**Comment by rfkrocktk** [comment]
Would anyone else like to sign the document and submit this code, maybe in
another pull request?

**Comment by ph** [comment]
close in favor or

**Comment by ph** [comment]
replaced by #46

**Pull request closed without merging**
