### PR TITLE
Allow the S3 input to gracefully handle multiple GZ blob

### PR DESCRIPTION
**Pull request by ph**
Some AWS service uses multiple blob of compressed data in the same file,
this commit make sure that the S3 input will try to read all the
available blob and not only the first one.

This PR also contains fixes for the aws eager loading issue.

Fixes: #101

### CODE REVIEW

**Comment by gmoskovicz** [comment]
Thank you @ph for taking care of this. Awesome.

**Comment by suyograo** [comment]
@ph did you forget the file `multiple_compressed_streams.gz`?

**Comment by suyograo** [comment]
Code LGTM. Waiting for travis

**Comment by ph** [comment]
Code is Green now travis.

**Pull request closed without merging**
